### ISSUE TITLE
wkhtmltopdf-binary v0.9.9.3 is feeling very lost right now.

### ISSUE THREAD

**Issue by tonyrosario** [pboling/gem_bench#14]
I noticed in the README that I can report a gem being lost or can contribute to fix the error.

Do you have any suggestions on how I would track this down and fix it?  Simply looking for a high-level overview and then I'll take a look.

Let me know if I need to post any additional info from my GemBench.check

**Comment by pboling** [comment]
This gem is basically just a premise of some simple rules like:
* Things with Railties need to be required at rails' boot.

So it searches through the bundled gem's source to find things that look like railties and whatever else I configured (can't recall if there was anything else).

1. There is a regex of gems that should be excluded, either because they can't be searched lexically (due to a compiled binary as may be the case here) or perhaps some strange text encoding.
2. There is, IIRC, also a regex to exclude specific file types (like `/.exe|.bin/`)

So to have GemBench ignore this gem, which seems like what we should do, or at least ignore the specific file causing it to fail with the "lost" warning, just add to the Regexes in the gem's source.

**Comment by pboling** [comment]
Gems to exclude, because GemBench was choking on them at the time I wrote it, are listed here:
https://github.com/pboling/gem_bench/blob/master/lib/gem_bench/team.rb#L4

**Comment by pboling** [comment]
I *think* you only get the "lost" error if you also got something like this above it:

```
  "[GemBench] checking #{file_path} failed due to unparseable file content"
```

Did you see anything like that?

**Comment by tonyrosario** [comment]
@pboling Great I didn't see any instances of unparseable file content but I'll dig deeper thanks to the info you provided.  I appreciate the help!

Also, note that this is happening on jruby-1.7.16.1
